/**
 * Creates a free Ethereal test inbox and writes credentials to .env.local
 * Run: npm run setup:email
 *
 * For production, replace with Gmail App Password or your SMTP provider:
 *   SMTP_HOST=smtp.gmail.com
 *   SMTP_PORT=587
 *   SMTP_USER=your@gmail.com
 *   SMTP_PASS=your-app-password
 *   NOTIFY_EMAIL=your@gmail.com
 */

const nodemailer = require("nodemailer");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Creating Ethereal test email account...\n");

  const testAccount = await nodemailer.createTestAccount();

  const envContent = `# Auto-generated by npm run setup:email
# Ethereal is for TESTING — emails appear at https://ethereal.email
SMTP_HOST=${testAccount.smtp.host}
SMTP_PORT=${testAccount.smtp.port}
SMTP_USER=${testAccount.user}
SMTP_PASS=${testAccount.pass}
NOTIFY_EMAIL=${testAccount.user}
`;

  const envPath = path.join(__dirname, "..", ".env.local");
  fs.writeFileSync(envPath, envContent);

  console.log("✅ Email credentials saved to .env.local\n");
  console.log("Test inbox:", testAccount.user);
  console.log("View sent emails at: https://ethereal.email/login");
  console.log("  User:", testAccount.user);
  console.log("  Pass:", testAccount.pass);
  console.log("\nFor real emails (Gmail):");
  console.log("  1. Enable 2FA on Google account");
  console.log("  2. Create App Password: https://myaccount.google.com/apppasswords");
  console.log("  3. Update .env.local with smtp.gmail.com credentials");
}

main().catch((err) => {
  console.error("Could not create Ethereal account:", err.message);
  console.log("\nManually create .env.local (copy from .env.local.example):");
  console.log("  SMTP_HOST=smtp.gmail.com");
  console.log("  SMTP_PORT=587");
  console.log("  SMTP_USER=your@gmail.com");
  console.log("  SMTP_PASS=your-16-char-app-password");
  console.log("  NOTIFY_EMAIL=your@gmail.com");
  process.exit(1);
});
